import type { Metadata } from "next";
import "./globals.css";
import { fonts } from "@/lib/font";

import { LoginModalProvider } from "@/contexts/login-modal-context"; // Import your LoginModal context provider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts}>
      <body className="font-sans">
        <LoginModalProvider>
          {children}
        </LoginModalProvider>
      </body>
    </html>
  );
}
